[package]
name = "first-test"
version = "0.1.0"
edition = "2021"

[dependencies]
ocl = "0.19"
pixels = "0.13.0"
env_logger = "0.10"
error-iter = "0.4"
log = "0.4"
winit = { version="0.29", features = ["rwh_05"] }
winit_input_helper = "0.16"
thiserror = "1.0"